export interface City {
  slug: string                   // 'sheffield'
  name: string                   // 'Sheffield'
  county: string                 // 'South Yorkshire'
  region: string                 // 'Yorkshire and the Humber'
  population: number             // 584,853
  
  // Geographic context
  postcodes: string[]            // ['S1', 'S2', 'S3', ...]
  neighbouringAreas: string[]    // ['Rotherham', 'Barnsley', 'Chesterfield']
  
  // Local context for content
  notableAreas: string[]         // ['Ecclesall', 'Hillsborough', 'Sharrow']
  characteristics: string        // 1-2 sentences about the city's housing/business mix
  housingProfile: string         // Description of dominant housing types
  
  // For internal linking
  nearbyCities: string[]         // Slugs of nearby cities for internal links
  
  // For overview content
  industryNote: string           // Local industry context
}

export const cities: City[] = [
  // Tier 1 — Major metros
  {
    slug: 'london',
    name: 'London',
    county: 'Greater London',
    region: 'London',
    population: 9540576,
    postcodes: ['E', 'EC', 'N', 'NW', 'SE', 'SW', 'W', 'WC'],
    neighbouringAreas: ['Watford', 'Croydon', 'Romford', 'Bromley', 'Kingston upon Thames'],
    notableAreas: ['Camden', 'Hackney', 'Greenwich', 'Wandsworth', 'Islington', 'Lambeth'],
    characteristics: 'A vast and varied housing market spanning Victorian terraces, Edwardian semis, post-war estates, and modern apartments across 32 boroughs and the City of London.',
    housingProfile: 'Property stock ranges from period terraces in Camden and Islington to riverside flats in Greenwich and large detached homes in outer boroughs like Bromley and Kingston.',
    nearbyCities: [],  // London is its own market
    industryNote: 'London tradespeople command higher rates due to higher cost of living and a property market with substantial renovation budgets.',
  },
  {
    slug: 'birmingham',
    name: 'Birmingham',
    county: 'West Midlands',
    region: 'West Midlands',
    population: 1157603,
    postcodes: ['B'],
    neighbouringAreas: ['Solihull', 'Dudley', 'Walsall', 'West Bromwich', 'Sutton Coldfield'],
    notableAreas: ['Edgbaston', 'Moseley', 'Harborne', 'Kings Heath', 'Erdington'],
    characteristics: 'The UK\'s second-largest city with a diverse property mix from Victorian terraces in Selly Oak to leafy suburban semis in Edgbaston and modern apartments in Brindleyplace.',
    housingProfile: 'Strong stock of Victorian and Edwardian housing in central districts, with extensive 1930s suburban development and significant new-build apartment stock in the city centre.',
    nearbyCities: ['wolverhampton', 'coventry'],
    industryNote: 'Birmingham\'s combination of city centre regeneration and suburban housing stock creates consistent demand across all trades.',
  },
  {
    slug: 'manchester',
    name: 'Manchester',
    county: 'Greater Manchester',
    region: 'North West',
    population: 568996,
    postcodes: ['M'],
    neighbouringAreas: ['Salford', 'Stockport', 'Oldham', 'Rochdale', 'Bolton'],
    notableAreas: ['Didsbury', 'Chorlton', 'Withington', 'Rusholme', 'Levenshulme'],
    characteristics: 'A rapidly regenerating northern city centre surrounded by established Victorian suburbs and newer commuter belts.',
    housingProfile: 'Significant Victorian terrace stock in inner suburbs, leafy semi-detached belts in Didsbury and Chorlton, and a growing high-rise apartment market in the regenerated city core.',
    nearbyCities: ['liverpool', 'leeds', 'sheffield'],
    industryNote: 'Manchester\'s ongoing regeneration creates particularly strong demand for renovation, extension, and commercial fit-out trades.',
  },
  {
    slug: 'leeds',
    name: 'Leeds',
    county: 'West Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 516298,
    postcodes: ['LS'],
    neighbouringAreas: ['Wakefield', 'Bradford', 'Halifax', 'Huddersfield'],
    notableAreas: ['Headingley', 'Roundhay', 'Chapel Allerton', 'Horsforth', 'Adel'],
    characteristics: 'A major financial and legal centre with substantial Victorian housing stock, expanding city centre apartment market, and prosperous suburban areas.',
    housingProfile: 'Dense Victorian back-to-back and terrace housing in inner suburbs, large stone-built semi-detached homes in north Leeds, and modern apartment developments around the city centre.',
    nearbyCities: ['bradford', 'wakefield', 'huddersfield', 'sheffield'],
    industryNote: 'Strong professional services economy supports premium trade work, particularly extensions, full renovations, and high-end fitted joinery.',
  },
  {
    slug: 'sheffield',
    name: 'Sheffield',
    county: 'South Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 584853,
    postcodes: ['S'],
    neighbouringAreas: ['Rotherham', 'Barnsley', 'Chesterfield', 'Doncaster'],
    notableAreas: ['Ecclesall', 'Hillsborough', 'Sharrow', 'Crookes', 'Nether Edge', 'Dore'],
    characteristics: 'England\'s largest pre-industrial city with stone-built Victorian terraces, leafy western suburbs, and a regenerating city centre.',
    housingProfile: 'Distinctive stone-built Victorian terraces dominating much of the city, with substantial detached stock in Dore, Totley, and the western Peak fringe, and modern apartment regeneration in the city centre.',
    nearbyCities: ['rotherham', 'barnsley', 'chesterfield', 'doncaster', 'leeds'],
    industryNote: 'Sheffield\'s housing stock is particularly suited to extension, loft conversion, and full renovation work, with a strong market for high-quality joinery and bespoke fitted furniture.',
  },
  {
    slug: 'liverpool',
    name: 'Liverpool',
    county: 'Merseyside',
    region: 'North West',
    population: 496770,
    postcodes: ['L'],
    neighbouringAreas: ['Birkenhead', 'St Helens', 'Bootle', 'Crosby', 'Wirral'],
    notableAreas: ['Allerton', 'Mossley Hill', 'Aigburth', 'Woolton', 'Calderstones'],
    characteristics: 'A historic maritime city with extensive Victorian terraced housing, Georgian quarters, and substantial inner-city regeneration.',
    housingProfile: 'Distinctive Liverpool red-brick terraced housing in Anfield, Toxteth, and Walton, contrasted with grand Georgian and Victorian villas in Sefton Park, Allerton, and Calderstones.',
    nearbyCities: ['manchester'],
    industryNote: 'Significant ongoing regeneration in Liverpool ONE, the docks, and Baltic Triangle creates demand for fit-out, refurbishment, and HVAC trades.',
  },
  {
    slug: 'newcastle',
    name: 'Newcastle upon Tyne',
    county: 'Tyne and Wear',
    region: 'North East',
    population: 300125,
    postcodes: ['NE'],
    neighbouringAreas: ['Gateshead', 'North Tyneside', 'South Tyneside', 'Sunderland'],
    notableAreas: ['Jesmond', 'Gosforth', 'Heaton', 'Fenham', 'Ouseburn'],
    characteristics: 'A regional capital with a famously vibrant city centre, substantial Tyneside flat stock, and prosperous northern suburbs.',
    housingProfile: 'Distinctive Tyneside flats (paired upper/lower flats) dominate inner suburbs, with Edwardian and Victorian villas in Jesmond and Gosforth, and significant 1930s and post-war suburban growth in Fenham and Kenton.',
    nearbyCities: ['sunderland'],
    industryNote: 'Newcastle\'s Tyneside flat stock creates specific demand for plumbing and electrical trades familiar with shared building infrastructure.',
  },
  {
    slug: 'bristol',
    name: 'Bristol',
    county: 'Bristol',
    region: 'South West',
    population: 472446,
    postcodes: ['BS'],
    neighbouringAreas: ['Bath', 'Weston-super-Mare', 'Clevedon', 'Yate'],
    notableAreas: ['Clifton', 'Redland', 'Cotham', 'Bedminster', 'Bishopston'],
    characteristics: 'A prosperous and culturally distinctive city with Georgian terraces, Victorian housing, and a strong creative and tech economy.',
    housingProfile: 'Magnificent Georgian terraces in Clifton, Victorian and Edwardian housing across Redland and Bishopston, with significant new development in Harbourside and Temple Quarter.',
    nearbyCities: [],
    industryNote: 'Bristol\'s prosperous professional and creative class supports strong demand for premium trade work, sustainable building practices, and high-end joinery.',
  },
  
  // Tier 2 — Strong regionals
  {
    slug: 'nottingham',
    name: 'Nottingham',
    county: 'Nottinghamshire',
    region: 'East Midlands',
    population: 337098,
    postcodes: ['NG'],
    neighbouringAreas: ['Mansfield', 'Newark', 'Beeston', 'West Bridgford'],
    notableAreas: ['West Bridgford', 'Mapperley', 'Sherwood', 'Wollaton', 'The Park'],
    characteristics: 'A thriving regional city with strong universities, professional employment, and a varied housing stock.',
    housingProfile: 'Victorian terraces in inner suburbs, significant 1930s suburban semi-detached growth, and substantial new-build apartment development around the city centre and Lace Market.',
    nearbyCities: ['derby', 'leicester', 'mansfield'],
    industryNote: 'Nottingham\'s student rental sector creates consistent demand for landlord-focused trade services, particularly Gas Safe certification and EICR testing.',
  },
  {
    slug: 'leicester',
    name: 'Leicester',
    county: 'Leicestershire',
    region: 'East Midlands',
    population: 368572,
    postcodes: ['LE'],
    neighbouringAreas: ['Loughborough', 'Hinckley', 'Coalville', 'Melton Mowbray'],
    notableAreas: ['Stoneygate', 'Knighton', 'Clarendon Park', 'Oadby', 'Wigston'],
    characteristics: 'A diverse and historic East Midlands city with strong manufacturing and retail sectors and varied housing stock.',
    housingProfile: 'Densely packed Victorian terraced housing in inner suburbs, substantial Edwardian and 1930s suburban growth, and prosperous detached stock in Stoneygate and Knighton.',
    nearbyCities: ['nottingham', 'derby', 'coventry'],
    industryNote: 'Leicester has a particularly active landlord market and strong demand for professional gas, electrical, and compliance work.',
  },
  {
    slug: 'coventry',
    name: 'Coventry',
    county: 'West Midlands',
    region: 'West Midlands',
    population: 345324,
    postcodes: ['CV'],
    neighbouringAreas: ['Warwick', 'Leamington Spa', 'Nuneaton', 'Solihull'],
    notableAreas: ['Earlsdon', 'Tile Hill', 'Cheylesmore', 'Allesley', 'Coundon'],
    characteristics: 'A heavily rebuilt post-war city with a mix of 1950s/60s housing, Edwardian suburbs, and ongoing regeneration.',
    housingProfile: 'Extensive post-war terraced and semi-detached stock following WWII reconstruction, with surviving Edwardian areas in Earlsdon and modern developments in regeneration zones.',
    nearbyCities: ['birmingham', 'leicester', 'wolverhampton'],
    industryNote: 'Coventry\'s ageing post-war housing stock creates strong demand for rewires, boiler replacements, and full-property modernisation.',
  },
  {
    slug: 'derby',
    name: 'Derby',
    county: 'Derbyshire',
    region: 'East Midlands',
    population: 261400,
    postcodes: ['DE'],
    neighbouringAreas: ['Burton upon Trent', 'Belper', 'Ashbourne', 'Long Eaton'],
    notableAreas: ['Allestree', 'Mickleover', 'Littleover', 'Spondon', 'Chaddesden'],
    characteristics: 'An East Midlands manufacturing centre with strong engineering employment, varied housing stock, and proximity to the Peak District.',
    housingProfile: 'Victorian and Edwardian terraced housing in central areas, significant 1930s suburban development in Allestree and Mickleover, and modern stock around the city periphery.',
    nearbyCities: ['nottingham', 'chesterfield', 'leicester'],
    industryNote: 'Derby\'s strong engineering economy supports premium trade work, with particular demand for high-end domestic projects and commercial fit-outs.',
  },
  {
    slug: 'stoke-on-trent',
    name: 'Stoke-on-Trent',
    county: 'Staffordshire',
    region: 'West Midlands',
    population: 258375,
    postcodes: ['ST'],
    neighbouringAreas: ['Newcastle-under-Lyme', 'Crewe', 'Stafford'],
    notableAreas: ['Trentham', 'Hartshill', 'Penkhull', 'Westlands', 'Wolstanton'],
    characteristics: 'A historic Potteries city of six federated towns with substantial Victorian and Edwardian housing stock and significant regeneration.',
    housingProfile: 'Dense Victorian terraced housing reflects the city\'s industrial heritage, with substantial Edwardian and inter-war suburbs and ongoing regeneration in central areas.',
    nearbyCities: ['wolverhampton'],
    industryNote: 'Stoke\'s ageing housing stock creates strong demand for renovation, rewiring, and heating system upgrades.',
  },
  {
    slug: 'wolverhampton',
    name: 'Wolverhampton',
    county: 'West Midlands',
    region: 'West Midlands',
    population: 263700,
    postcodes: ['WV'],
    neighbouringAreas: ['Walsall', 'Dudley', 'Cannock', 'Telford'],
    notableAreas: ['Tettenhall', 'Penn', 'Compton', 'Wightwick', 'Finchfield'],
    characteristics: 'A West Midlands market town with strong manufacturing heritage, Black Country character, and varied suburban housing.',
    housingProfile: 'Extensive Edwardian and Victorian terraces in central areas, prosperous detached stock in Tettenhall and Compton, and significant inter-war and post-war suburban growth.',
    nearbyCities: ['birmingham', 'stoke-on-trent', 'coventry'],
    industryNote: 'Wolverhampton has consistent demand across all trades, with particular strength in domestic renovation work.',
  },
  {
    slug: 'plymouth',
    name: 'Plymouth',
    county: 'Devon',
    region: 'South West',
    population: 264727,
    postcodes: ['PL'],
    neighbouringAreas: ['Saltash', 'Ivybridge', 'Tavistock'],
    notableAreas: ['Mannamead', 'Mutley', 'Plymstock', 'Hartley', 'Compton'],
    characteristics: 'A historic naval city with extensive post-war reconstruction, distinctive Plymouth limestone architecture, and a strong maritime economy.',
    housingProfile: 'Significant 1950s reconstruction housing following WWII bombing damage, surviving Victorian and Edwardian areas in Mutley and Mannamead, and modern naval/garrison housing.',
    nearbyCities: [],
    industryNote: 'Plymouth\'s reconstruction-era housing creates ongoing demand for renovation, modernisation, and energy-efficiency upgrades.',
  },
  {
    slug: 'southampton',
    name: 'Southampton',
    county: 'Hampshire',
    region: 'South East',
    population: 269781,
    postcodes: ['SO'],
    neighbouringAreas: ['Eastleigh', 'Romsey', 'Totton', 'Hedge End'],
    notableAreas: ['Bassett', 'Highfield', 'Bitterne', 'Shirley', 'Portswood'],
    characteristics: 'A major south coast port and university city with substantial Victorian and Edwardian housing and a strong professional sector.',
    housingProfile: 'Extensive Victorian terraced housing in central districts, prosperous Edwardian villas in Highfield and Bassett, and significant inter-war and post-war suburban development.',
    nearbyCities: ['portsmouth'],
    industryNote: 'Southampton\'s student rental market and professional housing stock support consistent demand for compliance, certification, and renovation trades.',
  },
  {
    slug: 'portsmouth',
    name: 'Portsmouth',
    county: 'Hampshire',
    region: 'South East',
    population: 208100,
    postcodes: ['PO'],
    neighbouringAreas: ['Havant', 'Fareham', 'Gosport', 'Waterlooville'],
    notableAreas: ['Southsea', 'North End', 'Cosham', 'Drayton', 'Old Portsmouth'],
    characteristics: 'A historic naval city built on Portsea Island with distinctive terraced housing and a strong military and student population.',
    housingProfile: 'Densely packed Victorian and Edwardian terraced housing dominates the island, with grander Victorian villas in Southsea and modern naval housing in newer districts.',
    nearbyCities: ['southampton'],
    industryNote: 'Portsmouth\'s dense terraced housing creates particular demand for plumbers and electricians familiar with party-wall and shared-system work.',
  },
  {
    slug: 'reading',
    name: 'Reading',
    county: 'Berkshire',
    region: 'South East',
    population: 174224,
    postcodes: ['RG'],
    neighbouringAreas: ['Wokingham', 'Bracknell', 'Henley-on-Thames', 'Newbury'],
    notableAreas: ['Caversham', 'Earley', 'Tilehurst', 'Lower Earley', 'Whitley'],
    characteristics: 'A prosperous Thames Valley town with strong professional and tech employment, varied housing, and high disposable incomes.',
    housingProfile: 'Victorian and Edwardian housing in central areas, substantial 1930s suburban growth, and modern professional housing in Lower Earley and the eastern districts.',
    nearbyCities: [],
    industryNote: 'Reading\'s prosperous professional class supports premium trade work, including high-end extensions, bespoke joinery, and renewable energy installations.',
  },
  {
    slug: 'cardiff',
    name: 'Cardiff',
    county: 'South Glamorgan',
    region: 'Wales',
    population: 372089,
    postcodes: ['CF'],
    neighbouringAreas: ['Newport', 'Penarth', 'Caerphilly', 'Barry'],
    notableAreas: ['Pontcanna', 'Roath', 'Cathays', 'Llandaff', 'Penylan'],
    characteristics: 'The Welsh capital with grand Edwardian housing, substantial Victorian terraces, and significant new bay-front development.',
    housingProfile: 'Distinctive Edwardian villas in Pontcanna and Cathays, dense Victorian terraces in Roath, and substantial post-war and modern development extending into the bay.',
    nearbyCities: [],
    industryNote: 'Cardiff has a particularly active landlord market driven by its university student population and a strong professional sector supporting premium domestic trade work.',
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    county: 'City of Edinburgh',
    region: 'Scotland',
    population: 526470,
    postcodes: ['EH'],
    neighbouringAreas: ['Leith', 'Musselburgh', 'Livingston', 'Dalkeith'],
    notableAreas: ['Stockbridge', 'Bruntsfield', 'Morningside', 'Marchmont', 'New Town'],
    characteristics: 'Scotland\'s capital with Georgian New Town, Victorian tenement housing, and a strong professional and tourism economy.',
    housingProfile: 'Famous Georgian New Town terraces, distinctive Victorian and Edwardian tenement flats throughout central districts, and substantial inter-war suburban housing in outer areas.',
    nearbyCities: [],
    industryNote: 'Edinburgh\'s tenement housing stock creates particular demand for plumbing, electrical, and structural trades familiar with shared infrastructure and Scottish building regulations.',
  },
  
  // Tier 3 — Midlands/North focus
  {
    slug: 'chesterfield',
    name: 'Chesterfield',
    county: 'Derbyshire',
    region: 'East Midlands',
    population: 88483,
    postcodes: ['S40', 'S41', 'S42', 'S43'],
    neighbouringAreas: ['Sheffield', 'Mansfield', 'Worksop', 'Bolsover'],
    notableAreas: ['Walton', 'Brockwell', 'Hasland', 'Ashgate', 'Newbold'],
    characteristics: 'A historic Derbyshire market town with the distinctive crooked spire, varied housing stock, and proximity to the Peak District.',
    housingProfile: 'Stone-built Victorian terraces in central areas, substantial inter-war and post-war suburban housing in Walton and Brockwell, and modern stock on the western edges towards the Peak District.',
    nearbyCities: ['sheffield', 'mansfield', 'derby'],
    industryNote: 'Chesterfield\'s position between major Yorkshire and East Midlands cities makes it a strong base for regional trade businesses serving multiple population centres.',
  },
  {
    slug: 'doncaster',
    name: 'Doncaster',
    county: 'South Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 109805,
    postcodes: ['DN'],
    neighbouringAreas: ['Sheffield', 'Rotherham', 'Barnsley', 'Worksop'],
    notableAreas: ['Bessacarr', 'Cantley', 'Wheatley', 'Balby', 'Hexthorpe'],
    characteristics: 'A South Yorkshire market town with strong railway heritage and substantial post-war housing.',
    housingProfile: 'Mix of Victorian terraced housing in central districts and extensive 1950s/60s suburban development, with modern estates on the southern edges.',
    nearbyCities: ['sheffield', 'rotherham', 'barnsley'],
    industryNote: 'Doncaster\'s ageing housing stock creates strong demand for heating system upgrades and full-property modernisation work.',
  },
  {
    slug: 'wakefield',
    name: 'Wakefield',
    county: 'West Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 99251,
    postcodes: ['WF'],
    neighbouringAreas: ['Leeds', 'Pontefract', 'Castleford', 'Dewsbury'],
    notableAreas: ['Sandal', 'Lupset', 'Outwood', 'Stanley', 'Crigglestone'],
    characteristics: 'A West Yorkshire cathedral city with stone-built Victorian housing and substantial suburban development.',
    housingProfile: 'Distinctive Yorkshire stone Victorian terraces, substantial 1930s suburban growth in Lupset and Sandal, and modern development on the southern fringes.',
    nearbyCities: ['leeds', 'huddersfield', 'doncaster'],
    industryNote: 'Wakefield benefits from proximity to Leeds while maintaining its own distinctive market for renovation and modernisation work.',
  },
  {
    slug: 'lincoln',
    name: 'Lincoln',
    county: 'Lincolnshire',
    region: 'East Midlands',
    population: 103813,
    postcodes: ['LN'],
    neighbouringAreas: ['Newark', 'Sleaford', 'Gainsborough'],
    notableAreas: ['Bailgate', 'West Parade', 'Birchwood', 'Bracebridge', 'Hartsholme'],
    characteristics: 'A historic East Midlands cathedral city with steep historic centre, university, and varied housing stock.',
    housingProfile: 'Historic stone-built housing in the upper city near the cathedral, Victorian and Edwardian terraces below the hill, and substantial 20th-century suburban growth.',
    nearbyCities: [],
    industryNote: 'Lincoln\'s student population and tourism economy support consistent demand across compliance, renovation, and rental property trades.',
  },
  {
    slug: 'mansfield',
    name: 'Mansfield',
    county: 'Nottinghamshire',
    region: 'East Midlands',
    population: 110500,
    postcodes: ['NG18', 'NG19'],
    neighbouringAreas: ['Nottingham', 'Chesterfield', 'Worksop', 'Sutton-in-Ashfield'],
    notableAreas: ['Mansfield Woodhouse', 'Forest Town', 'Berry Hill', 'Sutton-in-Ashfield'],
    characteristics: 'A former Nottinghamshire mining town with substantial post-industrial housing and ongoing regeneration.',
    housingProfile: 'Former colliery housing terraces, substantial post-war estate development, and modern infill on former industrial land.',
    nearbyCities: ['nottingham', 'chesterfield', 'worksop'],
    industryNote: 'Mansfield\'s ageing housing stock creates particular demand for boiler replacement, full rewires, and energy-efficiency upgrades.',
  },
  {
    slug: 'rotherham',
    name: 'Rotherham',
    county: 'South Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 109691,
    postcodes: ['S60', 'S61', 'S62', 'S63', 'S64', 'S65', 'S66'],
    neighbouringAreas: ['Sheffield', 'Doncaster', 'Barnsley'],
    notableAreas: ['Wickersley', 'Whiston', 'Bramley', 'Brinsworth', 'Wath upon Dearne'],
    characteristics: 'A South Yorkshire industrial town adjacent to Sheffield with mixed housing and a regenerating town centre.',
    housingProfile: 'Mix of Victorian terraces, post-war estate housing, and modern suburban growth in Wickersley and Bramley.',
    nearbyCities: ['sheffield', 'doncaster', 'barnsley'],
    industryNote: 'Rotherham\'s position adjacent to Sheffield makes it part of a continuous urban trade market.',
  },
  {
    slug: 'barnsley',
    name: 'Barnsley',
    county: 'South Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 96888,
    postcodes: ['S70', 'S71', 'S72', 'S73', 'S74', 'S75'],
    neighbouringAreas: ['Sheffield', 'Wakefield', 'Doncaster', 'Rotherham'],
    notableAreas: ['Worsbrough', 'Hoyland', 'Penistone', 'Wombwell', 'Cudworth'],
    characteristics: 'A historic South Yorkshire mining town with extensive ex-colliery housing and a regenerating town centre.',
    housingProfile: 'Substantial former mining village stock, post-war council estate development now largely owner-occupied, and modern suburban growth on the periphery.',
    nearbyCities: ['sheffield', 'rotherham', 'wakefield'],
    industryNote: 'Barnsley\'s housing stock has substantial energy-efficiency improvement potential, supporting strong demand for heating, insulation, and renewable trades.',
  },
  {
    slug: 'bradford',
    name: 'Bradford',
    county: 'West Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 349561,
    postcodes: ['BD'],
    neighbouringAreas: ['Leeds', 'Halifax', 'Keighley', 'Huddersfield'],
    notableAreas: ['Heaton', 'Manningham', 'Idle', 'Shipley', 'Bingley'],
    characteristics: 'A West Yorkshire former wool city with distinctive stone-built Victorian architecture and varied housing.',
    housingProfile: 'Famous Yorkshire stone Victorian terraces, grand mill-owner villas in Manningham and Heaton, and substantial inter-war and modern suburban development.',
    nearbyCities: ['leeds', 'huddersfield'],
    industryNote: 'Bradford\'s stone-built housing stock requires specialist knowledge for renovation, particularly for roof, pointing, and structural work.',
  },
  {
    slug: 'huddersfield',
    name: 'Huddersfield',
    county: 'West Yorkshire',
    region: 'Yorkshire and the Humber',
    population: 162949,
    postcodes: ['HD'],
    neighbouringAreas: ['Bradford', 'Halifax', 'Wakefield', 'Dewsbury'],
    notableAreas: ['Lindley', 'Edgerton', 'Marsh', 'Almondbury', 'Crosland Moor'],
    characteristics: 'A West Yorkshire town with strong textile heritage, distinctive stone-built Victorian housing, and proximity to the Peak District.',
    housingProfile: 'Stone-built Victorian terraced housing throughout central districts, substantial Edwardian villas in Edgerton, and Pennine-edge stone properties on the western fringes.',
    nearbyCities: ['leeds', 'bradford', 'wakefield'],
    industryNote: 'Huddersfield\'s stone housing stock and Pennine-edge location support specialist demand for heritage-aware trades and energy-efficiency work.',
  },
  {
    slug: 'sunderland',
    name: 'Sunderland',
    county: 'Tyne and Wear',
    region: 'North East',
    population: 174286,
    postcodes: ['SR'],
    neighbouringAreas: ['Newcastle', 'Durham', 'Washington', 'Houghton-le-Spring'],
    notableAreas: ['Ashbrooke', 'Roker', 'Fulwell', 'Tunstall', 'Silksworth'],
    characteristics: 'A North East port city with shipbuilding heritage, varied housing stock, and significant post-industrial regeneration.',
    housingProfile: 'Tyneside flat stock similar to Newcastle, substantial Victorian and Edwardian housing in Ashbrooke and Roker, and significant post-war estate development.',
    nearbyCities: ['newcastle'],
    industryNote: 'Sunderland\'s mix of period and post-war housing creates broad demand across all major trades, with particular need for energy-efficiency upgrades.',
  },
]
